baseURL = "http://www.eltink.net/"
title = "eltink.net"
languageCode = "en-us"
defaultContentLanguage = "en"
googleAnalytics = "UA-21965585-8"
enableRobotsTxt = true
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
